---
title: Network visualization
---
<!-- .refs is style for reference page (small text) -->
<style>
.refs {
   font-size: 16px;
}
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
.title-slide {
   background-color: #55bbff;
}
</style>
<!--    content: url(https://i.creativecommons.org/l/by-sa/4.0/88x31.png)
>
<!-- Limit image width and height -->
<style type="text/css">
img {     
  max-height: 560px;     
  max-width: 800px; 
}
</style>

```{r setup,echo=FALSE,message=FALSE}
library("knitr")
opts_chunk$set(echo=FALSE,fig.width=4,fig.height=4,out.width=400)
```

# Overview

## What is a network?

A visualization centered on pairwise interactions:

* A flight network
* A network of cooperative interactions between dolphins
* A network of aggressive interactions between chimpanzees
* A network of proteins and biochemical pathways

Interactors are generally indicated by _nodes_, and interactions by _edges_

## How are these interactions characterized?

* _Weighted_ networks have different importance to the edges
* In _directional_ networks, edges have direction
* In _multipartite_ networks, nodes are divided into two types that interact only with each other
	* almost always bipartite
* _Multimodal_ networks show different _types_ of links

## What are we trying to show?

* Relationships between particular nodes
* Patterns of clustering
* Paths and distances (six degrees of separation)
* Relationship between network structure and other variables

# Aesthetics

## Position

* May reflect the network structure
	* Usually by using force-directed algorithms
	* Balance desired qualities by simulating a physical system
	* Good layout is a hard problem

* Or something else about the data
	* most often physical location

## Other node aesthetics

* Size can be used for importance (should have a scaleable, physical interpretation)
	* Can be good for things about role in the network (e.g. betweenness, centrality)

* Color can be used for quantitative or qualitative attributes
	* Choose a color scale that reflects this role

* Shape can be used for qualitative attributes
	* It is possible to be creative about shape; e.g., use png icons

## Edge aesthetics

Strongly constrained; they're basically lines, and the nodes are drawn first

* Use width to indicate edge "weight" (nothing else)

* Use color to indicate edge type for a multi-modal graph

* Use arrows to indicate direction on a directional graph

* Curvature can be aesthetic (rarely) or can be used to get multi-modal edges out of each others' way

# Principles

## Preserve information

* Don't drop weights without a good reason
	* it may be OK to scale weights for aesthetic reasons

* Similarly for dropping specific edges

## Size matters

* Level of detail and messages will change a lot depending on how many nodes you have
	* Very big networks may show _only_ the pattern of node clustering

* If you have many nodes, but only a few important ones, it may be possible to follow the above edge principles
	* Rescale node size to improve visualization

* Communicate clearly about rescaling

# Resources

## Packages

* igraph and ggraph
* graphlayouts
* networks (does not play nicely with others)
* tidygraph

## Sites

* https://kateto.net/network-visualization
* FlowingData examples: https://flowingdata.com/category/visualization/network-visualization/

## Examples

* [Locate and read media data](https://github.com/mac-theobio/DataViz/blob/master/media.R)
* [Simple plots](https://github.com/mac-theobio/DataViz/blob/master/imedia.R)
* [ggplots](https://github.com/mac-theobio/DataViz/blob/master/ggmedia.R)
